### ISSUE TITLE
RuntimeError: `launch_passive` requires that the Python script be run under `mjpython` on macOS

### ISSUE THREAD

**Issue by mehdikhfifi** [kevinzakka/mink#22]
Not exactly sure what this error is inferring. Do the scripts actually open the mujoco engine? Would love some help debugging

(mujoco) mehdikhfifi@Mehdis-MacBook-Pro examples % python quadruped_go1.py 
Traceback (most recent call last):
  File "/Users/mehdikhfifi/Downloads/mink-main/examples/quadruped_go1.py", line 48, in <module>
    with mujoco.viewer.launch_passive(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mehdikhfifi/miniforge3/envs/mujoco/lib/python3.12/site-packages/mujoco/viewer.py", line 481, in launch_passive
    raise RuntimeError(
RuntimeError: `launch_passive` requires that the Python script be run under `mjpython` on macOS

**Comment by mehdikhfifi** [comment]
nvm found a solution:
https://openprompt.co/conversations/4594

**Comment by mehdikhfifi** [comment]
nvm found a solution:
https://openprompt.co/conversations/4594
